### ISSUE TITLE
[Suggestion] IDAPython Latest Commit Binaries

### ISSUE THREAD

**Issue by jnpl95** [idapython/bin#7]
Is it possible for someone to add the binaries for the latest commit of idapython? It'd be really helpful for everyone who doesn't want to download source and compile.

**Comment by aundro** [comment]
Hi,

that would mean each time anything is pushed to this repo, we would have to upload Windows, Linux & OSX binaries for both debug & release builds of IDAPython. Since we recently agreed to take pull requests that would be interesting to IDAPython, that might in theory mean we'd have to do it many times between releases, and we would very much like to avoid that kind of overhead.

If you don't want to recompile and/or modify IDAPython, why not use the one we ship with IDA?
