### ISSUE TITLE
IDA7.0  no moudle named "_idaapi"

### ISSUE THREAD

**Issue by kamike** [idapython/bin#8]
what's the "_idaapi",only idaapi.py

**Comment by aundro** [comment]
[sorry, meant to click 'comment', not 'close'.]

However… there's not much I can say here. There's no question, no context, … care to elaborate?

**Comment by kamike** [comment]
sorry,i use "IDA_Pro_v7.0_Portable",install Python27x64,download "idapython-6.9.0-python2.7-win.zip", Copy the whole "python" directory to %IDADIR%
Copy the contents of the "plugins" directory to the %IDADIR%\plugins\
Copy "python.cfg" to %IDADIR%\cfg
and reopen IDA，it's show error message "no moudle named "_idaapi",i don't what to do

**Comment by aundro** [comment]
One thing you can do, is actually use a non-pirate IDA version which, although considered pricey to some, comes with great support.

**Comment by NSExceptional** [comment]
@aundro I would if you would actually sell to me. The website says you don't deliver to free email accounts. I literally can't use your software because you won't let me buy it

Until then, I will continue to advocate for your great software and hope that one day one of my employers will buy a license I can use at work.
