### ISSUE TITLE
Can not initialize hexrays plugin in IDAPythonScript

### ISSUE THREAD

**Issue by yangshouguo** [idapython/bin#9]
It is the below code in my IDAPython script
`print idaapi.init_hexrays_plugin()`
But When i ran in command line mode such as `idal -Smyscript.py, bin.idb` it always returns false. What can i do to get true.

**Comment by aundro** [comment]
I cannot reproduce the problem. Since you are using 'idal', I can only assume you are either:
 - using IDA 6.x, or
 - using the compatibility IDA 7.x, x86 version
Are you certain you have a decompiler for that IDB? (i.e., if you press <Tab> in disassembly, does IDA show pseudo-code?)

It's also possible that there was a bug in those, that has been fixed since then.

**Comment by yangshouguo** [comment]
Thx. The IDA Pro I used is v7.0, and i am sure that i have the decompiler. The script i used is the IDAPython. According to my observation.  hexrays plugin was loaded after IDAPython loaded, maybe It's the reason why  idaapi.init_hexrays_plugin() not true.

**Comment by aundro** [comment]
That might be, indeed. Note however, that we don't really provide support here; please contact us at <support@hex-rays.com> if you have a license under support, and we'll gladly help you.

**Comment by NSExceptional** [comment]
@yangshouguo did you ever figure this out?
